name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - uses: leafo/gh-actions-lua@v9.1.0
        with:
          luaVersion: "5.4.4"

      - uses: leafo/gh-actions-luarocks@v4.3.0

      - name: setup
        run: |
          luarocks install busted

      - name: test
        run: |
          busted -c -v -o utfTerminal
          luacov

language: c
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - curl -Os https://uploader.codecov.io/latest/linux/codecov
  - chmod +x codecov
  - ./codecov
